### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jpcodering** [KamiKillertO/vscode-colorize#292]
- Issue Type: `Performance`
- Extension Name: `vscode-colorize`
- Extension Version: `0.8.13`
- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/tipografia/kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KamiKillertO** [comment]
@plasticode you forgot to upload the file ^^

**Comment by mahdizakizadeh** [comment]
I've the same issue

[kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt](https://github.com/KamiKillertO/vscode-colorize/files/3624981/kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt)

**Comment by BrunoS3D** [comment]
The extension is very good, but I noticed a performance theft from my machine just minutes after installation.

**Comment by KamiKillertO** [comment]
Thanks @mahdizakizadeh for the file, I'll have a look.
I'm well aware of the performance issues, I'm working on it.

However there's already ways to reduce/fix them.
Colorize have a lots of settings with default values that target a wide range of files/languages.
By changing those settings you can reduce the amount of work done by colorize everytimes you open a project or a file.

For exemple by default colorize generate background colors for every colors in the opened files, by setting `colorize.colorize_only_visible_beta` to true, colorize will only generate background for the visible part of the file(this setting can have huge impact when working on large files).

By default colorize generate background for SASS,LESS,CSS,STYLUS variables, but this also have some performance impact because the extension need to scan all files in a project in order to find the variables declarations. The setting `colorize.colorized_variables` let you define a list of variables that will be colorized. If you only use SASS change this setting to `colorize.colorized_variables: ["SASS"]` that way the extension will only search SASS variables.

All settings are listed [here](https://github.com/KamiKillertO/vscode-colorize#options-settings)

**Comment by dmcreativestudios** [comment]
@KamiKillertO just want to say thanks for all your hard work

**Comment by a7madgamal** [comment]
still getting vscode notification periodically although I enabled`colorize_only_visible_beta`
