### ISSUE TITLE
Why variable `tan` be coloried in TypeScript file?

### ISSUE THREAD

**Issue by tjx666** [KamiKillertO/vscode-colorize#415]
![Snipaste_2020-07-14_09-50-41](https://user-images.githubusercontent.com/41773861/87371294-97853d00-c5b7-11ea-849c-6219c8b5c296.png)

**Comment by KamiKillertO** [comment]
It's colorized because `tan` is a CSS color. You can either disable colorization for CSS colors or colorization in typescript files if it's bothering you. Check at the settings [colorize.languages-array](https://github.com/KamiKillertO/vscode-colorize#colorizelanguages-array) and [colorize.colorized_colors-array](https://github.com/KamiKillertO/vscode-colorize#colorizecolorized_colors-array)
